/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'totalSegments' : bigint,
  'totalCustomers' : bigint,
  'averageCustomerValue' : number,
  'topRevenueSegment' : string,
}
export interface Segment {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'ageMax' : bigint,
  'ageMin' : bigint,
  'description' : string,
  'incomeMax' : bigint,
  'incomeMin' : bigint,
  'revenueContribution' : number,
  'accountTypes' : Array<string>,
  'riskProfile' : string,
  'customerCount' : bigint,
}
export interface _SERVICE {
  'createSegment' : ActorMethod<[Segment], bigint>,
  'deleteSegment' : ActorMethod<[bigint], undefined>,
  'getAllSegments' : ActorMethod<[], Array<Segment>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getSegmentById' : ActorMethod<[bigint], Segment>,
  'seedSegments' : ActorMethod<[], undefined>,
  'updateSegment' : ActorMethod<[bigint, Segment], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];