/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Segment = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'ageMax' : IDL.Nat,
  'ageMin' : IDL.Nat,
  'description' : IDL.Text,
  'incomeMax' : IDL.Nat,
  'incomeMin' : IDL.Nat,
  'revenueContribution' : IDL.Float64,
  'accountTypes' : IDL.Vec(IDL.Text),
  'riskProfile' : IDL.Text,
  'customerCount' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'totalSegments' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
  'averageCustomerValue' : IDL.Float64,
  'topRevenueSegment' : IDL.Text,
});

export const idlService = IDL.Service({
  'createSegment' : IDL.Func([Segment], [IDL.Nat], []),
  'deleteSegment' : IDL.Func([IDL.Nat], [], []),
  'getAllSegments' : IDL.Func([], [IDL.Vec(Segment)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getSegmentById' : IDL.Func([IDL.Nat], [Segment], ['query']),
  'seedSegments' : IDL.Func([], [], []),
  'updateSegment' : IDL.Func([IDL.Nat, Segment], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Segment = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'ageMax' : IDL.Nat,
    'ageMin' : IDL.Nat,
    'description' : IDL.Text,
    'incomeMax' : IDL.Nat,
    'incomeMin' : IDL.Nat,
    'revenueContribution' : IDL.Float64,
    'accountTypes' : IDL.Vec(IDL.Text),
    'riskProfile' : IDL.Text,
    'customerCount' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'totalSegments' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
    'averageCustomerValue' : IDL.Float64,
    'topRevenueSegment' : IDL.Text,
  });
  
  return IDL.Service({
    'createSegment' : IDL.Func([Segment], [IDL.Nat], []),
    'deleteSegment' : IDL.Func([IDL.Nat], [], []),
    'getAllSegments' : IDL.Func([], [IDL.Vec(Segment)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getSegmentById' : IDL.Func([IDL.Nat], [Segment], ['query']),
    'seedSegments' : IDL.Func([], [], []),
    'updateSegment' : IDL.Func([IDL.Nat, Segment], [], []),
  });
};

export const init = ({ IDL }) => { return []; };