/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DashboardStats {
    totalSegments: bigint;
    totalCustomers: bigint;
    averageCustomerValue: number;
    topRevenueSegment: string;
}
export interface Segment {
    id: bigint;
    name: string;
    createdAt: bigint;
    ageMax: bigint;
    ageMin: bigint;
    description: string;
    incomeMax: bigint;
    incomeMin: bigint;
    revenueContribution: number;
    accountTypes: Array<string>;
    riskProfile: string;
    customerCount: bigint;
}
export interface backendInterface {
    createSegment(segment: Segment): Promise<bigint>;
    deleteSegment(id: bigint): Promise<void>;
    getAllSegments(): Promise<Array<Segment>>;
    getDashboardStats(): Promise<DashboardStats>;
    getSegmentById(id: bigint): Promise<Segment>;
    seedSegments(): Promise<void>;
    updateSegment(id: bigint, segment: Segment): Promise<void>;
    _initializeAccessControlWithSecret(secret: string): Promise<void>;
    saveDatasetMetadata(filename: string, rowCount: bigint, columns: Array<string>, blobId: string): Promise<bigint>;
    getDatasetHistory(): Promise<Array<{ id: bigint; filename: string; uploadedAt: bigint; rowCount: bigint; columns: Array<string>; blobId: string; status: string }>>;
    deleteDataset(id: bigint): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createSegment(arg0: Segment): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSegment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSegment(arg0);
            return result;
        }
    }
    async deleteSegment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSegment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSegment(arg0);
            return result;
        }
    }
    async getAllSegments(): Promise<Array<Segment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSegments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSegments();
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getSegmentById(arg0: bigint): Promise<Segment> {
        if (this.processError) {
            try {
                const result = await this.actor.getSegmentById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSegmentById(arg0);
            return result;
        }
    }
    async seedSegments(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSegments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSegments();
            return result;
        }
    }
    async updateSegment(arg0: bigint, arg1: Segment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSegment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSegment(arg0, arg1);
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await (this.actor as any)._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any)._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async saveDatasetMetadata(arg0: string, arg1: bigint, arg2: Array<string>, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).saveDatasetMetadata(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).saveDatasetMetadata(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getDatasetHistory(): Promise<Array<{ id: bigint; filename: string; uploadedAt: bigint; rowCount: bigint; columns: Array<string>; blobId: string; status: string }>> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).getDatasetHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).getDatasetHistory();
            return result;
        }
    }
    async deleteDataset(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).deleteDataset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).deleteDataset(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
